name: Build Assembly Code for iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode environment
        run: |
          sudo xcode-select --switch /Applications/Xcode.app
          echo "SDKROOT=$(xcrun --sdk iphoneos --show-sdk-path)" >> $GITHUB_ENV

      - name: Build assembly code
        run: |
          xcrun -sdk iphoneos clang -arch arm64 -mios-version-min=13.0 -c getpid.s -o getpid.o
          xcrun -sdk iphoneos clang -arch arm64 -mios-version-min=13.0 -o getpid getpid.o -e _main -lSystem -nostdlib

      - name: List output files
        run: ls -la getpid