name: iOS Jailbreak Plugin Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app

    - name: Setup iOS SDK
      run: |
        SDKROOT=$(xcrun --sdk iphoneos --show-sdk-path)
        echo "SDKROOT=$SDKROOT" >> $GITHUB_ENV

    - name: List directory contents
      run: ls -la

    - name: Compile main.mm
      run: |
        xcrun -sdk iphoneos clang++ -c main.mm -o main.o -arch arm64 -mios-version-min=14.0 -std=c++17

    - name: Assemble main.s
      run: |
        xcrun -sdk iphoneos clang -c main.s -o main_asm.o -arch arm64 -mios-version-min=14.0

    - name: Link object files
      run: |
        xcrun -sdk iphoneos clang++ main.o main_asm.o -o main -arch arm64 -mios-version-min=14.0 -framework Foundation -framework CoreFoundation -lc++ -std=c++17

    - name: Create DEBIAN directory structure
      run: |
        mkdir -p DEBIAN
        echo "Package: myplugin" > DEBIAN/control
        echo "Version: 1.0" >> DEBIAN/control
        echo "Section: Tweaks" >> DEBIAN/control
        echo "Architecture: iphoneos-arm64" >> DEBIAN/control
        echo "Depends: mobilesubstrate" >> DEBIAN/control
        echo "Maintainer: Your Name <your.email@example.com>" >> DEBIAN/control
        echo "Description: My iOS jailbreak plugin" >> DEBIAN/control

    - name: Copy binary to DEBIAN directory
      run: |
        mkdir -p DEBIAN/usr/lib/myplugin
        cp main DEBIAN/usr/lib/myplugin/

    - name: Build DEB package
      run: |
        dpkg-deb --build DEBIAN myplugin.deb

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ios-jailbreak-plugin
        path: myplugin.deb
