name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app

    - name: Setup iOS SDK
      run: |
        SDKROOT=$(xcrun --sdk iphoneos --show-sdk-path)
        echo "SDKROOT=$SDKROOT" >> $GITHUB_ENV

    - name: List directory contents
      run: ls -la

    - name: Verify file existence
      run: |
        if [ ! -f "内存模块.c" ]; then echo "内存模块.c not found!"; exit 1; fi
        if [ ! -f "c_main.c" ]; then echo "c_main.c not found!"; exit 1; fi
        if [ ! -f "查找进程.c" ]; then echo "查找进程.c not found!"; exit 1; fi
        if [ ! -f "main.s" ]; then echo "main.s not found!"; exit 1; fi

    - name: Compile C files
      run: |
        xcrun -sdk iphoneos clang -c "内存模块.c" -o "内存模块.o" -arch arm64 -mios-version-min=14.0 -Wno-incompatible-pointer-types
        xcrun -sdk iphoneos clang -c "c_main.c" -o "c_main.o" -arch arm64 -mios-version-min=14.0
        xcrun -sdk iphoneos clang -c "查找进程.c" -o "查找进程.o" -arch arm64 -mios-version-min=14.0

    - name: Assemble main.s
      run: |
        xcrun -sdk iphoneos clang -c "main.s" -o "main.o" -arch arm64 -mios-version-min=14.0

    - name: Link object files
      run: |
        xcrun -sdk iphoneos clang "main.o" "c_main.o" "内存模块.o" "查找进程.o" -o "main" -arch arm64 -mios-version-min=14.0 -framework Foundation -framework CoreFoundation

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ios-arm64-binary
        path: main
