name: Build Assembly Code for iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
  ACTIONS_RUNNER_DEBUG: true

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode environment
        run: |
          sudo xcode-select --switch /Applications/Xcode.app
          echo "SDKROOT=$(xcrun --sdk iphoneos --show-sdk-path)" >> $GITHUB_ENV
          echo "$(xcrun -f clang)" >> $GITHUB_PATH
          echo "$(xcrun -f as)" >> $GITHUB_PATH

      - name: Display environment info
        run: |
          xcodebuild -version
          xcrun --sdk iphoneos --show-sdk-path
          echo $PATH

      - name: Build assembly code
        run: |
          set -x

          xcrun -sdk iphoneos as -v -arch arm64 -o main.o main.s

      - name: List output files
        run: ls -la

      - name: Display file information
        run: |
          file main
          otool -hv main
          echo "Object file content:"
          hexdump -C main.o | head -n 20

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ARM64
          path: |
            *.o
            main
          retention-days: 30