name: Build Assembly Code for iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode environment
        run: |
          sudo xcode-select --switch /Applications/Xcode.app
          echo "SDKROOT=$(xcrun --sdk iphoneos --show-sdk-path)" >> $GITHUB_ENV

      - name: Build assembly code
        run: |
          xcrun -sdk iphoneos clang -arch arm64 -mios-version-min=13.0 -c getpid.s -o getpid.o
          xcrun -sdk iphoneos clang -arch arm64 -mios-version-min=13.0 -o getpid getpid.o -e _main -lSystem -nostdlib

      - name: List output files
        run: ls -la

      - name: Display file information
        run: |
          file getpid
          otool -hv getpid
          echo "Object file content:"
          hexdump -C getpid.o | head -n 20

      - name: Upload artifact (only on failure)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: ios-assembly-binary
          path: |
            getpid
            getpid.o
          retention-days: 3

      - name: Clean up old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 week'
          skip-recent: 5