name: iOS Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app

    - name: Setup iOS SDK
      run: |
        SDKROOT=$(xcrun --sdk iphoneos --show-sdk-path)
        echo "SDKROOT=$SDKROOT" >> $GITHUB_ENV

    - name: List directory contents
      run: ls -la

    - name: Compile main.mm
      run: |
        xcrun -sdk iphoneos clang++ -c main.mm -o main.o -arch arm64 -mios-version-min=14.0 -std=c++17

    - name: Assemble main.s
      run: |
        xcrun -sdk iphoneos clang -c main.s -o main_asm.o -arch arm64 -mios-version-min=14.0

    - name: Link object files
      run: |
        xcrun -sdk iphoneos clang++ main.o main_asm.o -o main -arch arm64 -mios-version-min=14.0 -framework Foundation -framework CoreFoundation -lc++ -std=c++17

    - name: Create .deb package
      run: |
        mkdir -p package/DEBIAN
        mkdir -p package/usr/local/bin

        # Copy the compiled binary to the package
        cp main package/usr/local/bin/

        # Create control file
        echo "Package: com.yourcompany.yourapp" > package/DEBIAN/control
        echo "Name: YourApp" >> package/DEBIAN/control
        echo "Depends: mobilesubstrate" >> package/DEBIAN/control
        echo "Version: 1.0-1" >> package/DEBIAN/control
        echo "Architecture: iphoneos-arm" >> package/DEBIAN/control
        echo "Description: Your app description" >> package/DEBIAN/control
        echo "Maintainer: Your Name <your.email@example.com>" >> package/DEBIAN/control
        echo "Author: Your Name <your.email@example.com>" >> package/DEBIAN/control
        echo "Section: Utilities" >> package/DEBIAN/control

        # Build the .deb package
        dpkg-deb --build package

    - name: Upload .deb artifact
      uses: actions/upload-artifact@v2
      with:
        name: ios-deb-package
        path: ./package.deb
