name: iOS ARM64 Assembly Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install iOS toolchain
      run: |
        brew update
        brew install --cask xcode
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        brew install cctools
    
    - name: Set up environment
      run: |
        echo "SDKROOT=$(xcrun --sdk iphoneos --show-sdk-path)" >> $GITHUB_ENV
        echo "$(xcrun --sdk iphoneos -f as)" >> $GITHUB_PATH
    
    - name: Assemble
      run: |
        as -arch arm64 -o mmap_memory.o mmap_memory.s
      
    - name: Link
      run: |
        ld -arch arm64 -ios_version_min 12.0 -o mmap_memory mmap_memory.o -lSystem -syslibroot $SDKROOT
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: mmap_memory
        path: mmap_memory