name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app

    - name: Setup iOS SDK
      run: |
        SDKROOT=$(xcrun --sdk iphoneos --show-sdk-path)
        echo "SDKROOT=$SDKROOT" >> $GITHUB_ENV

    - name: List directory contents
      run: ls -la

    - name: Compile C file
      run: |
        xcrun -sdk iphoneos clang -c c_main.c -o c_main.o -arch arm64 -mios-version-min=14.0

    - name: Link object file
      run: |
        xcrun -sdk iphoneos clang c_main.o -o main -arch arm64 -mios-version-min=14.0 -framework Foundation -framework CoreFoundation

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ios-arm64-binary
        path: main
