name: Build Memory Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew update
        brew install gcc

    - name: Build
      run: |
        gcc -c -I/usr/include/mach
        gcc -c main.c -o main.o
        gcc  main.o -o memory_server

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: memory-server
        path: memory_server