name: Build Assembly Code for iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode environment
        run: |
          sudo xcode-select --switch /Applications/Xcode.app
          echo "SDKROOT=$(xcrun --sdk iphoneos --show-sdk-path)" >> $GITHUB_ENV

      - name: Build assembly code
        run: |
          # 编译每个汇编文件
          xcrun -sdk iphoneos clang -arch arm64 -mios-version-min=13.0 -c main.s -o main.o
          xcrun -sdk iphoneos clang -arch arm64 -mios-version-min=13.0 -c get_pid.s -o get_pid.o
          xcrun -sdk iphoneos clang -arch arm64 -mios-version-min=13.0 -c print_number.s -o print_number.o
          # 链接生成可执行文件
          xcrun -sdk iphoneos clang -arch arm64 -mios-version-min=13.0 -o main main.o get_pid.o print_number.o -e _main -lSystem -nostdlib

      - name: List output files
        run: ls -la

      - name: Display file information
        run: |
          file main
          otool -hv main
          echo "Object file content:"
          hexdump -C main.o | head -n 20
          hexdump -C get_pid.o | head -n 20
          hexdump -C print_number.o | head -n 20

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ARM64
          path: |
            main
          retention-days: 30
