name: Build Assembly Code for iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode environment
        run: |
          sudo xcode-select --switch /Applications/Xcode.app
          echo "SDKROOT=$(xcrun --sdk iphoneos --show-sdk-path)" >> $GITHUB_ENV

      - name: Build assembly code
        run: |
          # 编译 C 文件
          xcrun -sdk iphoneos clang -arch arm64 -mios-version-min=13.0 -c print_number.c -o print_number.o
          
          # 汇编汇编文件
          xcrun -sdk iphoneos as -arch arm64 -o main.o main.s
          
          # 链接生成可执行文件
          xcrun -sdk iphoneos clang -arch arm64 -mios-version-min=13.0 main.o  print_number.o -o main

      - name: List output files
        run: ls -la

      - name: Display file information
        run: |
          file main
          otool -hv main
          echo "Object file content:"
          hexdump -C main.o | head -n 20
          hexdump -C get_pid.o | head -n 20
          hexdump -C print_number.o | head -n 20

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ARM64
          path: |
            main
          retention-days: 30