name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app

    - name: Setup iOS SDK
      run: |
        SDKROOT=$(xcrun --sdk iphoneos --show-sdk-path)
        echo "SDKROOT=$SDKROOT" >> $GITHUB_ENV

    - name: Compile C files
      run: |
        clang -c 内存模块.c -o 内存模块.o -target arm64-apple-ios -isysroot $SDKROOT
        clang -c c_main.txt -o c_main.o -target arm64-apple-ios -isysroot $SDKROOT

    - name: Assemble main.s
      run: |
        as -arch arm64 -o main.o main.s

    - name: Link object files
      run: |
        ld -o main main.o c_main.o 内存模块.o -lSystem -syslibroot $SDKROOT -arch arm64 -platform_version ios 14.0 14.0

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ios-arm64-binary
        path: main