name: iOS ARM64 Assembly Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Set up environment
      run: |
        echo "SDKROOT=$(xcrun --sdk iphoneos --show-sdk-path)" >> $GITHUB_ENV
        echo "$(xcrun --sdk iphoneos -f clang)" >> $GITHUB_PATH
    
    - name: Assemble
      run: |
        xcrun --sdk iphoneos clang -arch arm64 -c memory_read.s -o memory_read.o -mios-version-min=12.0

    - name: Link
      run: |
        xcrun --sdk iphoneos clang -arch arm64 -isysroot $SDKROOT -mios-version-min=12.0 -o memory_read memory_read.o -framework Foundation -framework CoreFoundation
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: mmap_memory
        path: mmap_memory